version: '3.8'

services:
  freewrite-api:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - DEBUG=true
      # Firebase configuration (set these in .env file)
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID:-}
      - FIREBASE_PRIVATE_KEY_ID=${FIREBASE_PRIVATE_KEY_ID:-}
      - FIREBASE_PRIVATE_KEY=${FIREBASE_PRIVATE_KEY:-}
      - FIREBASE_CLIENT_EMAIL=${FIREBASE_CLIENT_EMAIL:-}
      - FIREBASE_CLIENT_ID=${FIREBASE_CLIENT_ID:-}
      - FIREBASE_AUTH_URI=${FIREBASE_AUTH_URI:-https://accounts.google.com/o/oauth2/auth}
      - FIREBASE_TOKEN_URI=${FIREBASE_TOKEN_URI:-https://oauth2.googleapis.com/token}
      # Google Gemini configuration
      - GOOGLE_API_KEY=${GOOGLE_API_KEY:-}
    volumes:
      - ./backend:/app
      - ./shared:/app/shared
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - freewrite-network

networks:
  freewrite-network:
    driver: bridge

volumes:
  freewrite-data: